# Generated by Django 5.1.7 on 2025-07-02 23:29

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_curso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/alunos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
